
services:
  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dayquest-cdn
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      STORAGE_TYPE: "local"
      SERVER_PORT: "${SERVER_PORT}"
    volumes:
      - "${LOCAL_STORAGE_PATH}:/data"
    pull_policy: build
