services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: dayquest-minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: minio server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - dayquest-network

  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dayquest-cdn
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      STORAGE_TYPE: "minio"
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      RAW_VIDEOS_BUCKET: "${RAW_VIDEOS_BUCKET}"
      DATABASE_DSN: "${DATABASE_DSN}"
      VIDEOS_BUCKET: "${VIDEOS_BUCKET}"
      FAILED_BUCKET: "${FAILED_BUCKET}"
      SERVER_PORT: "${SERVER_PORT}"
      THUMBNAIL_BUCKET: "${THUMBNAIL_BUCKET}"
    depends_on:
      - minio
    pull_policy: build
    networks:
      - dayquest-network


volumes:
  minio_data:

networks:
  dayquest-network:
    external: true
    name: dayquest-network
